


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$begin
  insert into public.profiles (user_uuid, username, profile_image_url)
  values (
    new.id,
    case
      when new.raw_user_meta_data ? 'login' then new.raw_user_meta_data->>'login'
      when new.raw_user_meta_data ? 'preferred_username' then new.raw_user_meta_data->>'preferred_username'
      when new.raw_user_meta_data ? 'user_name' then new.raw_user_meta_data->>'user_name'
      when new.raw_user_meta_data ? 'name' then new.raw_user_meta_data->>'name'
      when  new.raw_user_meta_data ? 'username' then new.raw_user_meta_data->> 'username'
      else 'user_' || left(new.id::text, 8)
    end,
    case
      when new.raw_user_meta_data ? 'avatar_url' then new.raw_user_meta_data->>'avatar_url'
      when new.raw_user_meta_data ? 'picture' then new.raw_user_meta_data->>'picture'
      else 
      new.raw_user_meta_data ->> 'profile_image_url'
    end
  );

  return new;  
end;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."dms" (
    "dm_id" bigint NOT NULL,
    "dm_name" "text",
    "dm_icon" "text",
    CONSTRAINT "dms_gc_icon_check" CHECK (("length"("dm_icon") < 200)),
    CONSTRAINT "dms_gc_name_check" CHECK (("length"("dm_name") <= 50))
);


ALTER TABLE "public"."dms" OWNER TO "postgres";


COMMENT ON TABLE "public"."dms" IS 'Direct messages and group chats';



ALTER TABLE "public"."dms" ALTER COLUMN "dm_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dms_gc_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dms_messages" (
    "message_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "message_content" "text" DEFAULT ''::"text" NOT NULL,
    "message_image_url" "text",
    "dm_id" bigint,
    "user_uuid" "uuid" NOT NULL,
    "is_edited" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."dms_messages" OWNER TO "postgres";


ALTER TABLE "public"."dms_messages" ALTER COLUMN "message_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dms_messages_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dms_users" (
    "user_uuid" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "dm_id" bigint NOT NULL
);


ALTER TABLE "public"."dms_users" OWNER TO "postgres";


COMMENT ON TABLE "public"."dms_users" IS '1 row is one user';



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "message_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "message_content" "text" DEFAULT ''::"text" NOT NULL,
    "user_uuid" "uuid",
    "is_edited" boolean DEFAULT false NOT NULL,
    "message_image_url" "text",
    CONSTRAINT "messages_message_content_check" CHECK (("length"("message_content") <= 1201)),
    CONSTRAINT "messages_message_image_url_check" CHECK (("length"("message_image_url") < 500))
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


COMMENT ON TABLE "public"."messages" IS 'A list of all messages ever sent';



ALTER TABLE "public"."messages" ALTER COLUMN "message_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_message_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "user_id" bigint NOT NULL,
    "profile_image_url" "text",
    "username" "text" DEFAULT ''::"text" NOT NULL,
    "user_uuid" "uuid" NOT NULL,
    "role" "text",
    CONSTRAINT "profiles_profile_image_url_check" CHECK (("length"("profile_image_url") < 200)),
    CONSTRAINT "profiles_username_check" CHECK (("length"("username") < 30))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


COMMENT ON TABLE "public"."profiles" IS 'A list of users and all permanent or user updated information';



ALTER TABLE "public"."profiles" ALTER COLUMN "user_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."dms"
    ADD CONSTRAINT "dms_gc_id_key" UNIQUE ("dm_id");



ALTER TABLE ONLY "public"."dms_messages"
    ADD CONSTRAINT "dms_messages_message_id_key" UNIQUE ("message_id");



ALTER TABLE ONLY "public"."dms_messages"
    ADD CONSTRAINT "dms_messages_pkey" PRIMARY KEY ("message_id");



ALTER TABLE ONLY "public"."dms"
    ADD CONSTRAINT "dms_pkey" PRIMARY KEY ("dm_id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_message_id_key" UNIQUE ("message_id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("message_id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_id_key" UNIQUE ("user_id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_name_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_uuid");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_user_uuid_key" UNIQUE ("user_uuid");



CREATE UNIQUE INDEX "dms_users_user_uuid_dm_id_idx" ON "public"."dms_users" USING "btree" ("user_uuid", "dm_id");



ALTER TABLE ONLY "public"."dms_messages"
    ADD CONSTRAINT "dms_messages_dm_id_fkey" FOREIGN KEY ("dm_id") REFERENCES "public"."dms"("dm_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dms_messages"
    ADD CONSTRAINT "dms_messages_user_uuid_fkey" FOREIGN KEY ("user_uuid") REFERENCES "public"."profiles"("user_uuid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dms_users"
    ADD CONSTRAINT "dms_users_dm_id_fkey" FOREIGN KEY ("dm_id") REFERENCES "public"."dms"("dm_id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."dms_users"
    ADD CONSTRAINT "dms_users_user_uuid_fkey" FOREIGN KEY ("user_uuid") REFERENCES "public"."profiles"("user_uuid") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_user_uuid_fkey" FOREIGN KEY ("user_uuid") REFERENCES "public"."profiles"("user_uuid") ON UPDATE CASCADE ON DELETE SET DEFAULT;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "users_user_uuid_fkey" FOREIGN KEY ("user_uuid") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Enable read access for all users" ON "public"."messages" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Enable update for users based on user_uuid" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "user_uuid")) WITH CHECK (("auth"."uid"() = "user_uuid"));



ALTER TABLE "public"."dms" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dms_messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."dms_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."messages";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."dms" TO "anon";
GRANT ALL ON TABLE "public"."dms" TO "authenticated";
GRANT ALL ON TABLE "public"."dms" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dms_gc_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dms_gc_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dms_gc_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dms_messages" TO "anon";
GRANT ALL ON TABLE "public"."dms_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."dms_messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dms_messages_message_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dms_messages_message_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dms_messages_message_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dms_users" TO "anon";
GRANT ALL ON TABLE "public"."dms_users" TO "authenticated";
GRANT ALL ON TABLE "public"."dms_users" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_message_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_message_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_message_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."users_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


